version: '3'

services:
  discovery:
    build: discovery
    container_name: discovery
    ports:
      - "8761:8761"
    depends_on:
      - log-shipper
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224

  gateway:
    build: gateway
    container_name: gateway
    ports:
      - "8889:8889"
    depends_on:
      - discovery
      - log-shipper
    environment:
      - JAVA_OPTS=-DDISCOVERY_SERVER=http://discovery:8761/eureka
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224

  quotes:
    build: quotes
    container_name: quotes
    ports:
      - "8890:8890"
    depends_on:
      - discovery
      - log-shipper
    environment:
      - JAVA_OPTS=-DDISCOVERY_SERVER=http://discovery:8761/eureka
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224

  greeter:
    build: greeter
    container_name: greeter
    ports:
      - "8891:8891"
    depends_on:
      - discovery
      - log-shipper
    environment:
      - JAVA_OPTS=-DDISCOVERY_SERVER=http://discovery:8761/eureka
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224

  log-shipper:
    build: log-shipper
    container_name: log-shipper
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    links:
      - "elasticsearch"
    depends_on:
      - "elasticsearch"
      - "kibana"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - "discovery.type=single-node"
    expose:
      - "9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.1
    container_name: kibana
    ports:
      - "5601:5601"
    links:
      - "elasticsearch"
    depends_on:
      - "elasticsearch"
